# ============================================================================
#                         Copyright 2020 Gennaro Prota
#
#                   Licensed under the 3-Clause BSD License.
#              (See accompanying file 3_CLAUSE_BSD_LICENSE.txt or
#               <https://opensource.org/licenses/BSD-3-Clause>.)
# ____________________________________________________________________________
#
#       GitHub continuous integration.
#
#       This configures the builds (plus tests) to run automatically on
#       push and other events.
# ----------------------------------------------------------------------------


#       TODO:
#         there's a lot of duplication in this file: can't 'runs-on' use
#         a matrix??
# ----------------------------------------------------------------------------

name: builds_and_tests
on:   [push, pull_request]

jobs:
  clang-on-linux:
    name: Clang on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang++, clang++-8, clang++-9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Builds and tests
        env:
          system: unix
          compiler: clang
          compiler_command: ${{matrix.compiler}}
        run: BREEZE_ROOT=` pwd ` && export BREEZE_ROOT && make

  gcc-on-linux:
    name: GCC on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++, g++-8, g++-9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Builds and tests
        env:
          system: unix
          compiler: gcc
          compiler_command: ${{matrix.compiler}}
        run: BREEZE_ROOT=` pwd ` && export BREEZE_ROOT && make

  clang-on-macos:
    name: Clang on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ clang++ ]

    steps:
      - uses: actions/checkout@v2
      - name: Builds and tests
        env:
          system: unix
          compiler: clang
          compiler_command: ${{matrix.compiler}}

          #     Is there a way to avoid turning off this option?
          # ------------------------------------------------------------------
          cpp_extra_options: -Wno-poison-system-directories
        run: BREEZE_ROOT=` pwd ` && export BREEZE_ROOT && make

  gcc-on-macos:
    name: GCC on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ g++-8, g++-9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Builds and tests
        env:
          system: unix
          compiler: gcc
          compiler_command: ${{matrix.compiler}}
        run: BREEZE_ROOT=` pwd ` && export BREEZE_ROOT && make

  #     As of this writing (December 28, 2020), GitHub Actions doesn't
  #     directly support FreeBSD. But the macOS machines have VirtualBox
  #     installed, so we run FreeBSD in a VirtualBox virtual machine
  #     hosted by macOS.
  #
  #     For reference, see:
  #
  #       <https://github.com/marketplace/actions/freebsd-vm>.
  # --------------------------------------------------------------------------
  gcc-on-freebsd:
    name: GCC on FreeBSD
    runs-on: macos-latest
    env:
      system: unix
      compiler: gcc
    steps:
    - uses: actions/checkout@v2
    - uses: vmactions/freebsd-vm@v0.0.9
      with:
        run: |
          setenv ASSUME_ALWAYS_YES  YES
          pkg install gmake
          setenv BREEZE_ROOT ` pwd `
          make
